# vim:ft=confini

## upstream: https://codeberg.org/NRK/mpv-toolbox/src/branch/master/mfpbar/mfpbar.conf

# values are in percentage:
pbar_height=1.6
pbar_minimized_height=0.5

pbar_color=C0CAF5
pbar_bg_color=16161EF7
pbar_fullscreen_hide=yes


cachebar_height=0.35
cachebar_color=565F89
cachebar_uncached_color=292E42F7

# what to show in the right hand side of the timeline.
# valid options are `time-remaining` and `playtime-remaining`:
timeline_rhs=time-remaining

hover_bar_color=7AA2F7

font_color=C0CAF5
font_size=35
# horizontal font padding:
font_pad=4
font_border_width=2
font_border_color=000000

# trigger range for the progressbar.
# uses pixel count, percentage can also be used:
proximity=40

preview_border_width=2
preview_border_color=7AA2F7

max_thumb_size=256

chapter_marker_size=5
chapter_marker_color=7AA2F7
chapter_marker_border_width=1
chapter_marker_border_color=16161E
# proximity for triggering chapter snapping. 0 to disable chapter snapping.
# can use either pixel or percentage as `proximity`:
chapter_proximity=0.64%

minimize_timeout=3
maximize_timeout=1.5
maximize_on_seek=yes
