repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        args: ["-q"]
        types: [nix]
        language: system

      - id: stylua
        name: styLua
        entry: stylua
        types: [lua]
        language: system
