o script-binding mfpbar/maximize
P script-binding mfpbar/maximize


h     seek -5
l     seek  5
LEFT  seek -30
RIGHT seek  30

j    add volume -1
k    add volume  1
DOWN add volume -3
UP   add volume  3

t cycle sub
T cycle sub down

Ctrl+l       ab-loop
Ctrl+Shift+l cycle-values loop-file "inf" "no"


[ add chapter -1
] add chapter  1

{ multiply speed 1/1.1
} multiply speed 1.1
