input-ipc-server=/tmp/mpv.sock


keep-open=yes
save-watch-history=yes
save-position-on-quit=yes

hwdec=auto

# audio in discord screenshare only works with pulseaudio:
ao=pulse
volume=70

# the directory is defined by ./scripts/screenshot_dirs.lua:
screenshot-template="%F [%P]"

sub-auto=fuzzy
sub-file-paths=sub:Sub:subtitles:Subtitles

audio-file-auto=fuzzy
audio-file-paths=audio:Audio:sound:Sound

ytdl-raw-options-append=sub-langs=en.*,ru.*


# `mfpbar` and ./scripts/osd_volume_msgs.lua are used instead:
osc=no
osd-level=0

osd-font="JetBrainsMono NFM"

background-color="#F71A1B26"
osd-outline-color="#16161E"
osd-color="#C0CAF5"

sub-ass-override=force

sub-border-size=2.5
sub-scale=1.1
sub-border-size=2.5
sub-shadow-offset=1
