-- local schedule, config = require("schedule"), require("config")
-- local map = vim.keymap.set
--
-- schedule.later(function()
--     vim.pack.add({
--         config.github("cbochs/grapple.nvim"),
--     })
--
--     local grapple = require("grapple")
--     local Settings = require("grapple.settings")
--
--     local default_settings = Settings:new()
--
--     grapple.setup({
--         icons = true,
--         quick_select = "123456789",
--         statusline = {
--             include_icon = false,
--         },
--         tag_hook = function(window)
--             -- Toggle tag for current file
--             window:map("n", "a", function()
--                 window:close()
--                 grapple.toggle()
--                 grapple.open_tags()
--             end)
--
--             default_settings.tag_hook(window)
--         end,
--     })
--
--     map("n", ";", "<Cmd>Grapple toggle_tags<CR>")
-- end)
