# vim:ft=confini

[Appearance]
color_scheme_path=~/.local/share/color-schemes/TokyoNight.colors
custom_palette=true
icon_theme=breeze-dark
standard_dialogs=xdgdesktopportal
style=Klassy

[Fonts]
fixed="JetBrainsMono Nerd Font,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
general="Noto Sans,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
