promptToReturnFromSubprocess: false
notARepository: quit

update:
  method: never

git:
  log:
    order: default
  paging:
    colorArg: always
    pager: delta --paging=never

keybinding:
  universal:
    prevBlock-alt2: <left>
    nextBlock-alt2: <right>
    quit: Q
    prevItem: k
    nextItem: j
    scrollUpMain-alt1: <Up>
    scrollDownMain-alt1: <Down>
  files:
    commitChanges: C
    commitChangesWithEditor: c
  commits:
    renameCommitWithEditor: r
    renameCommit: R

customCommands:
  - key: q
    context: global
    output: log
    command: |-
      _lazygit nvim_term_send close
  - key: <tab>
    context: global
    output: log
    command: |-
      _lazygit nvim_term_send tabprevious
  - key: <backtab>
    context: global
    output: log
    command: |-
      _lazygit nvim_term_send tabnext
  - key: <C-t>
    context: files
    output: log
    command: |-
      _nvim_diffview file {{ .SelectedPath }}
  - key: <C-t>
    context: commitFiles
    output: log
    command: |-
      _nvim_diffview commit_file {{ .SelectedCommit.Hash }} {{ .SelectedPath }}
  - key: <C-t>
    context: stash
    output: log
    command: |-
      _nvim_diffview stash_entry {{ .SelectedStashEntry.Index }}
  - key: <C-t>
    context: commits
    output: log
    command: |-
      _nvim_diffview commits {{ .SelectedCommitRange.From }} {{ .SelectedCommitRange.To }}
  - key: <C-t>
    context: subCommits
    output: log
    command: |-
      _nvim_diffview commits {{ .SelectedCommitRange.From }} {{ .SelectedCommitRange.To }}
  - key: <C-t>
    context: reflogCommits
    output: log
    command: |-
      _nvim_diffview commits {{ .SelectedCommitRange.From }} {{ .SelectedCommitRange.To }}
  - key: <C-t>
    context: localBranches
    output: log
    command: |-
      _nvim_diffview local_branch {{ .SelectedLocalBranch.Name }}
  - key: <C-t>
    context: remoteBranches
    output: log
    command: |-
      _nvim_diffview remote_branch {{ .SelectedRemoteBranch.RemoteName }} {{ .SelectedRemoteBranch.Name }}

os:
  edit: |-
    _lazygit edit_file {{filename}}

  editAtLine: |-
    _lazygit edit_file_at_line {{filename}} {{line}}

  openDirInEditor: |-
    _lazygit edit_file {{dir}}

gui:
  border: single
  showNumstatInFilesView: true
  scrollHeight: 15
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  statusPanelView: allBranchesLog
  nerdFontsVersion: "3"

  # upstream: https://github.com/folke/tokyonight.nvim/blob/main/extras/lazygit/tokyonight_night.yml
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
