import = ["/home/narek/.config/alacritty/alacritty-theme/themes/catppuccin_mocha.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"


[font]
size = 15
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
[font.normal]

family = "JetBrainsMono Nerd Font"
style = "Regular"


[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = true
startup_mode = "Maximized"
padding = { x = 0, y = 0 }

